language: php

php:
  - '5.4'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - hhvm

services:
  - mysql

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev